name: moirae
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.10.*

  - pip
  - pip:
    # Basics
    - tqdm
    - matplotlib
    - pytables

    - jupyterlab
    - -e ..[test,docs,thevenin]
