name: moirae
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.9.*

  # Basics
  - tqdm
  - matplotlib

  - pip
  - pip:
    - battery-data-toolkit
    - jupyterlab
    - -e ..[test,docs]
