name: moirae
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.9.*

  # Basics
  - tqdm
  - matplotlib
  - h5py
  - pytables

  # Thevenin
  - scikits_odes_sundials

  - pip
  - pip:
    - battery-data-toolkit
    - jupyterlab
    - -e ..[test,docs,thevenin]
