name: Python Package

on:
  push:
  pull_request:
  schedule:
  - cron: '0 12 * * 1'

defaults:
  run:
    shell: bash -el {0}  # Lets conda work

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v3
        with:
            environment-file: dev/environment.yml
            activate-environment: test
            auto-activate-base: true
            auto-update-conda: false
            remove-profiles: true
            architecture: x64
            clean-patched-environment-file: true
            run-post: true
            use-mamba: false
            miniforge-version: latest
      - name: Lint with flake8
        run: |
          flake8 moirae/ tests
      - name: Test with pytest
        run: |
          pytest --cov=moirae tests
      - name: Test documentation notebooks
        if: ${{ runner.os == 'Linux' }}
        run: |
          pip install jupyter matplotlib
          home_dir=`pwd`
          for notebook in `find docs -name "*.ipynb"`; do
             cd `dirname $notebook`
             jupyter execute `basename $notebook`
             cd $home_dir
          done
      - name: Coveralls
        run: |
          pip install coveralls
          coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
